version: '3.8'

services:
  makerspet-mini-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: makerspet-mini-web:latest
    container_name: makerspet-mini-web
    network_mode: host
    privileged: true
    
    volumes:
      - ./maps:/app/maps:Z
      - ./logs:/app/logs:Z
      - ./config:/app/config:Z
      - ./web:/app/web:Z
      - ./launch:/app/launch:Z
    
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RCUTILS_COLORIZED_OUTPUT=1
    
    restart: unless-stopped
    
    stdin_open: true
    tty: true
